# Generated by Django 5.2.1 on 2025-05-21 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_favorite_unique_favorite_user_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_recipes', to='api.ingredient', verbose_name='Ингредиент'),
        ),
    ]
