# Generated by Django 5.2.1 on 2025-05-13 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_unit_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='title',
            new_name='name',
        ),
    ]
