# Generated by Django 5.2.1 on 2025-05-13 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_title_ingredient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cook_time',
            new_name='cooking_time',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
    ]
