# Generated by Django 5.2.1 on 2025-05-13 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_cook_time_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
