# Generated by Django 5.2.1 on 2025-05-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_shoppingcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='user',
            new_name='author',
        ),
    ]
