# Generated by Django 5.2.1 on 2025-05-14 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_shoppingcart_unique_shopping_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='created_at',
        ),
    ]
