volumes:
  pg_data:
  static:
  media:

networks:
  default:
    driver: bridge
    name: foodgram_network

services:
  db:
    image: postgres:17.3
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - default

  backend:
    container_name: foodgram-backend
    build: ../backend/
    env_file:
      - .env
    volumes:
      - static:/app/backend_static/
      - media:/app/media/
    depends_on:
      - postgres
    networks:
      - default

  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - static:/usr/share/nginx/html/api/static/
      - media:/usr/share/nginx/html/api/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    networks:
      - default